name: mac
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting the environment up.
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: | 
        source configure.sh "$VNC_USER_PASSWORD" "$VNC_PASSWORD" "$NGROK_AUTH_TOKEN"

    - name: Setup Neovim nightly
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: nightly

    - name: Configure Render plugin
      run: |
        mkdir -p "$HOME/.local/share/nvim/site/pack/mikesmithgh/start/"
        cp -r . "$HOME/.local/share/nvim/site/pack/mikesmithgh/start/render.nvim/"
        mkdir -p "$HOME/.config/nvim"
        cat <<'EOF' >> "$HOME/.config/nvim/init.lua"

        require('render').setup({
        -- notify = {
        --   level = vim.log.levels.OFF,
        -- },
        })
        -- vim.defer_fn(function()
        --   require('render.core').render()
        -- end, 2000)

        EOF

    - name: Configure Gruvsquirrel plugin
      run: |
        mkdir -p "$HOME/.local/share/nvim/site/pack/mikesmithgh/start/"
        cd "$HOME/.local/share/nvim/site/pack/mikesmithgh/start/"
        git clone https://github.com/mikesmithgh/gruvsquirrel.nvim.git
        cat <<'EOF' >> "$HOME/.config/nvim/init.lua"

        vim.cmd([[colorscheme gruvsquirrel]])

        EOF



    - name: ngrok is now listening to VNC connections on...
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
